services:
  - type: web
    name: java-project-72
    runtime: docker
    plan: free
    envVars:
      - key: PORT
        value: "8080"
      - key: JAVA_HOME
        value: "/usr/lib/jvm/temurin-21-jdk-amd64"